name: Run Rijksmuseum API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection
      run: newman run ./path-to-your-collection.json --environment ./path-to-your-environment.json
    
    - name: Run Postman Collection with HTML report
      run: newman run ./path-to-your-collection.json --reporters cli,html --reporter-html-export results/report.html
    

      
