name: Run Rijksmuseum API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html 

    #- name: Run Postman Collection
     # run: newman run ./rijksmuseum-api-collection.json --environment ./rijksmuseum_postman_environment.json

    - name: Create Results Directory
      run: mkdir -p results
    
    - name: Run Postman Collection with HTML report
      run: newman run ./rijksmuseum-api-collection.json --environment ./Test.postman_environment.json --reporters cli,html --reporter-html-export results/report.html --suppress-exit-code || exit 0

    - name: Upload HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: results/report.html
